definition = {
    "name": "standard",
    "cards": [
        { "name": "A♠", "count": 1, "description": "Ace of Spades" },
        { "name": "2♠", "count": 1, "description": "Two of Spades" },
        { "name": "3♠", "count": 1, "description": "Three of Spades" },
        { "name": "4♠", "count": 1, "description": "Four of Spades" },
        { "name": "5♠", "count": 1, "description": "Five of Spades" },
        { "name": "6♠", "count": 1, "description": "Six of Spades" },
        { "name": "7♠", "count": 1, "description": "Seven of Spades" },
        { "name": "8♠", "count": 1, "description": "Eight of Spades" },
        { "name": "9♠", "count": 1, "description": "Nine of Spades" },
        { "name": "10♠", "count": 1, "description": "Ten of Spades" },
        { "name": "J♠", "count": 1, "description": "Jack of Spades" },
        { "name": "Q♠", "count": 1, "description": "Queen of Spades" },
        { "name": "K♠", "count": 1, "description": "King of Spades" },

        { "name": "A♥", "count": 1, "description": "Ace of Hearts" },
        { "name": "2♥", "count": 1, "description": "Two of Hearts" },
        { "name": "3♥", "count": 1, "description": "Three of Hearts" },
        { "name": "4♥", "count": 1, "description": "Four of Hearts" },
        { "name": "5♥", "count": 1, "description": "Five of Hearts" },
        { "name": "6♥", "count": 1, "description": "Six of Hearts" },
        { "name": "7♥", "count": 1, "description": "Seven of Hearts" },
        { "name": "8♥", "count": 1, "description": "Eight of Hearts" },
        { "name": "9♥", "count": 1, "description": "Nine of Hearts" },
        { "name": "10♥", "count": 1, "description": "Ten of Hearts" },
        { "name": "J♥", "count": 1, "description": "Jack of Hearts" },
        { "name": "Q♥", "count": 1, "description": "Queen of Hearts" },
        { "name": "K♥", "count": 1, "description": "King of Hearts" },

        { "name": "A♦", "count": 1, "description": "Ace of Diamonds" },
        { "name": "2♦", "count": 1, "description": "Two of Diamonds" },
        { "name": "3♦", "count": 1, "description": "Three of Diamonds" },
        { "name": "4♦", "count": 1, "description": "Four of Diamonds" },
        { "name": "5♦", "count": 1, "description": "Five of Diamonds" },
        { "name": "6♦", "count": 1, "description": "Six of Diamonds" },
        { "name": "7♦", "count": 1, "description": "Seven of Diamonds" },
        { "name": "8♦", "count": 1, "description": "Eight of Diamonds" },
        { "name": "9♦", "count": 1, "description": "Nine of Diamonds" },
        { "name": "10♦", "count": 1, "description": "Ten of Diamonds" },
        { "name": "J♦", "count": 1, "description": "Jack of Diamonds" },
        { "name": "Q♦", "count": 1, "description": "Queen of Diamonds" },
        { "name": "K♦", "count": 1, "description": "King of Diamonds" },

        { "name": "A♣", "count": 1, "description": "Ace of Clubs" },
        { "name": "2♣", "count": 1, "description": "Two of Clubs" },
        { "name": "3♣", "count": 1, "description": "Three of Clubs" },
        { "name": "4♣", "count": 1, "description": "Four of Clubs" },
        { "name": "5♣", "count": 1, "description": "Five of Clubs" },
        { "name": "6♣", "count": 1, "description": "Six of Clubs" },
        { "name": "7♣", "count": 1, "description": "Seven of Clubs" },
        { "name": "8♣", "count": 1, "description": "Eight of Clubs" },
        { "name": "9♣", "count": 1, "description": "Nine of Clubs" },
        { "name": "10♣", "count": 1, "description": "Ten of Clubs" },
        { "name": "J♣", "count": 1, "description": "Jack of Clubs" },
        { "name": "Q♣", "count": 1, "description": "Queen of Clubs" },
        { "name": "K♣", "count": 1, "description": "King of Clubs" },
    ],
}
